this.loadOrder = {};

var exists      = Npm.require('fs').existsSync;
var pathResolve = Npm.require('path').resolve;

var sourceExists = function(source) {
  return exists(pathResolve('packages/load-order-config', source));
};

Package.describe({
  name    : 'imkost:load-order-config',
  version : '0.2.0',
  summary : 'This package is automatically generated by imkost:load-order',
});

Package.registerBuildPlugin({
  name: 'load-order',
  npmDependencies: {
    'glob'   : '5.0.5',
    'mkdirp' : '0.5.0',
    'rimraf' : '2.3.2'
  },
  use: [ 'coffeescript@1.0.6' ],
  sources: [
      'load-order-config.js',
      'load-order-config.coffee',
      'load-order.min.js'
    ].filter(function(source) {
      return sourceExists(source);
    })
});
